### ISSUE TITLE
GenServer terminating (FunctionClauseError): no function clause matching in Tzdata.Util.first_matching_weekday_in_month/4

### ISSUE THREAD

**Issue by joaothallis** [joaothallis/key#77]
View details in Rollbar: [https://rollbar.com/joaothallis/key/items/6/](https://rollbar.com/joaothallis/key/items/6/)

```
Traceback (most recent call last):
  File "lib/tzdata/util.ex", line 73, in Tzdata.Util.first_matching_weekday_in_month/4 (tzdata)
  File "lib/tzdata/util.ex", line 329, in Tzdata.Util.time_for_rule/2 (tzdata)
  File "lib/tzdata/period_builder.ex", line 161, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
  File "lib/tzdata/period_builder.ex", line 180, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
  File "lib/tzdata/period_builder.ex", line 185, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
  File "lib/tzdata/period_builder.ex", line 180, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
  File "lib/tzdata/period_builder.ex", line 185, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
  File "lib/tzdata/period_builder.ex", line 180, in Tzdata.PeriodBuilder.calc_periods_for_year/9 (tzdata)
GenServer terminating (FunctionClauseError): no function clause matching in Tzdata.Util.first_matching_weekday_in_month/4
```
```elixir
Tzdata.Util.first_matching_weekday_in_month/4 arguments:
1932
4
7
[]
```
Occurrences:
```
Timestamp
2019-07-04 05:53 pm
        03 09:53 pm
        02 08:43 pm
        01 07:43 pm

**Comment by joaothallis** [comment]
Fixed in version 1.0.1 of Timex: https://github.com/lau/tzdata/blob/d632a2adbefd435becdc6c3bfa87c8c48b8f8048/CHANGELOG.md#101---2019-07-01
